// Code generated by hertz generator.

package main

import (
	handler "hertz/demo/biz/handler"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)
	r.POST("/post", handler.PostTest)
	r.POST("/postJson", handler.PostJsonTest)

	// your code ...
}
