// Code generated by hertz generator.

package handler

import (
	"context"
	"fmt"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Ping .
func Ping(ctx context.Context, c *app.RequestContext) {

	// 获取?stu_id=2
	value, exist := c.GetQuery("stu_id")
	// 只获取值 valeu = c.Query("stu_id")
	if !exist {
		fmt.Println("没有查询参数stu_id")
	} else {
		fmt.Printf("获取的stu_id值 = %s", value)
	}

	c.JSON(consts.StatusOK, utils.H{
		"message": "pong",
	})
}

func PostTest(ctx context.Context, c *app.RequestContext) {
	value, exist := c.GetPostForm("username")
	if !exist {
		fmt.Println("username 为空")
	} else {
		fmt.Printf("username = %s\n", value)
	}
	c.JSON(consts.StatusOK, utils.H{
		"message": "post form method",
	})
}

type user struct {
	UserName string `json:"username" form:"username"`
}

func (user *user) ToString() (str string) {
	str = "UserName = " + user.UserName
	return
}

func PostJsonTest(ctx context.Context, c *app.RequestContext) {
	user := user{}
	c.BindJSON(&user)
	fmt.Println(user)
	fmt.Println(user.ToString())

	c.JSON(consts.StatusOK, utils.H{
		"message": "post json method",
	})
}
